### PR TITLE
deftype HtmlRendered

### PR DESCRIPTION
**Pull request by ajchemist**
I've changed the returns of both `rum/render-html` and `rum/render-static-markup`, and added rum/render-html-str, rum/render-static-markup-str.

I think this would be more natural for string interpolation than using `(str ~{a} ~{b})` or `(format "%s" ...)`

### CODE REVIEW

**Comment by ajchemist** [comment]
It seems everything works ok till now...... : http://ajchemist.github.io/rum/

**Comment by tonsky** [comment]
Most of the changes are fine, but I’m having hard time understanding what’s the idea behind `HtmlRenderer` type? Why do we need that?

**Comment by ajchemist** [comment]
HtmlRender**ed** exactly.

hmm in existing code

``` clojure
(rum/render-static-markup
 [:html
  [:head]
  [:body
   [:.example
    [:.example-title "Controls"]
    [:#controls (rum/render-html (controls/controls))]]]])
```

would emit html string that inner `rum/render-html` part is escaped like below. but I think this is not ideal for component snippet interpolation.

``` html
<html><head></head><body><div class=\"example\"><div
class=\"example-title\">Controls</div><div id=\"controls\">&lt;dl
data-reactroot=&quot;&quot; data-reactid=&quot;1&quot;
data-react-checksum=&quot;-948899190&quot;&gt;&lt;dt
data-reactid=&quot;2&quot;&gt;Color: &lt;/dt&gt;&lt;dd
data-reactid=&quot;3&quot;&gt;&lt;input type=&quot;text&quot;
value=&quot;#FA8D97&quot; style=&quot;width:100px;&quot;
data-reactid=&quot;4&quot;/&gt;&lt;/dd&gt;&lt;dt
data-reactid=&quot;5&quot;&gt;Clone: &lt;/dt&gt;&lt;dd
data-reactid=&quot;6&quot;&gt;&lt;input type=&quot;text&quot;
value=&quot;#FA8D97&quot; style=&quot;width:100px;&quot;
data-reactid=&quot;7&quot;/&gt;&lt;/dd&gt;&lt;dt
data-reactid=&quot;8&quot;&gt;Color: &lt;/dt&gt;&lt;dd
data-reactid=&quot;9&quot;&gt;&lt;span
data-reactid=&quot;10&quot;&gt;0&lt;/span&gt;&lt;!-- react-text: 11 --&gt;
watches&lt;!-- /react-text --&gt;&lt;/dd&gt;&lt;dt
data-reactid=&quot;12&quot;&gt;Tick: &lt;/dt&gt;&lt;dd
data-reactid=&quot;13&quot;&gt;&lt;input type=&quot;text&quot;
value=&quot;167&quot; style=&quot;width:100px;&quot;
data-reactid=&quot;14&quot;/&gt;&lt;!-- react-text: 15 --&gt; ms&lt;!--
/react-text --&gt;&lt;/dd&gt;&lt;dt
data-reactid=&quot;16&quot;&gt;Time:&lt;/dt&gt;&lt;dd
data-reactid=&quot;17&quot;&gt;&lt;span
data-reactid=&quot;18&quot;&gt;0&lt;/span&gt;&lt;!-- react-text: 19 --&gt;
watches&lt;!-- /react-text
--&gt;&lt;/dd&gt;&lt;/dl&gt;</div></div></body></html>

```

So I thought It would be good that there is no-escape **type** like `HtmlRendered`.

**Comment by ajchemist** [comment]
Additionally, IMO It's not that bad idea that once `src` which is passed through `rum/render*` fn should be treated as rendered object.

**Comment by tonsky** [comment]
The idea was that you render once, on a top level, just as you mount once. If you need to set unescaped html, you can always use `innerHtml`. Like other web frameworks, we can provide something like RawString for embedding unescaped strings, but I prefer it to be explicitly called instead of relying on that implicitly. This is “secure by default” approach. What do you think?

**Comment by ajchemist** [comment]
oh, I see. Let me think about that aspect.

or Maybe, how about consider `HtmlRendered` type privately? ( I mean ^:private )

**Comment by tonsky** [comment]
I still don’t see why is it needed, even privately. Do you have a case in mind?

**Comment by ajchemist** [comment]
Not particularly now, maybe I just wanna another syntatic sugar.

**Comment by ajchemist** [comment]
Alright, @tonsky I agree your approach, It feels I've thought too much plain. This would be another can of worms.

Thanks for the hard thinking.

**Pull request closed without merging**
