### PR TITLE
Updated React to 0.13 and added context methods.

### PR DESCRIPTION
**Pull request by currentoor**
Context methods are being used by React libraries like material-ui but they were not in the Rum API.

### CODE REVIEW

**Comment by ajchemist** [comment]
I think `target/main.js` will be compiled as `:advacned` option. `build.boot` provide `advanced-opts` task, so you can simply do

```
boot advanced-opts
rm -r target/rum.* target/out
```

**Comment by currentoor** [comment]
@aJchemist are you saying `target/main.js` needs advanced compilation?

I tried those two commands and there was no change, according to git.

**Comment by ajchemist** [comment]
Oops. try this,

```
boot -s examples advanced-opts cljs
```

or

```
boot advanced
C-c # (Cancel watcher)
```

**Comment by currentoor** [comment]
Good catch, thanks.

**Comment by ajchemist** [comment]
Great! But it seems you missed **-s examples** on

```
boot -s examples advanced-opts cljs
```

line.

https://github.com/currentoor/rum/blob/eef3efa2b6ed2a2d6ecf3579cdb257124de82552/target/main.js#L281 maybe ended with 

```
return React.createElement("div",null,a,b)}),b=cj(S.c(new T(null,1,5,V,[a],null),new T(null,1,5,V,[xk],null)),"our-src");return N(function(a,b){return function(){function a(b){var d=null;if(0<arguments.length){for(var d=0,e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new t(e,0)}return c.call(this,d)}function c(a){return nj(b,lj(a),M([null],0))}a.C=0;a.B=function(a){a=v(a);return c(a)};a.v=c;return a}()}(a,b),new q(null,1,[sh,b],null))}();ij(yk.D?yk.D():yk.call(null),Bj("context"));
```

**Comment by ajchemist** [comment]
Oops, already known issue #35. 
~--------------------------------------------------------------------------------------------
`:advanced` compilation works fine.

But compling with `:none`, Some warnings follow.

```
Warning: Don't set .props.:rum/state of the React component <static-timer />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <forced-timer />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <colored-clock />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. The element was created by reactive-timer. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <reactive-timer />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. react.inc.js:19588:7
"Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of bmi-component. See https://fb.me/react-warning-keys for more information." react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <bmi-component />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <input />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. The element was created by controls. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <watches-count />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. The element was created by controls. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <controls />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. react.inc.js:19588:7
"Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of bclock. See https://fb.me/react-warning-keys for more information." react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <bit />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. The element was created by bclock. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <render-count />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. The element was created by bclock. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <bclock />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <rcell />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. The element was created by art-rboard. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <board-stats />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. The element was created by art-rboard. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <art-rboard />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <art-cell />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. The element was created by artboard. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <board-stats />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. The element was created by artboard. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <artboard />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. react.inc.js:19588:7
"Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of val-form. See https://fb.me/react-warning-keys for more information." react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <validating-input />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. The element was created by val-form. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <restricting-input />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. The element was created by val-form. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <restricting-input-native />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. The element was created by val-form. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <val-form />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <stateful />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. react.inc.js:19588:7
"Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of tree. See https://fb.me/react-warning-keys for more information." react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <tree />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. The element was created by tree. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <tree />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. react.inc.js:19588:7
Warning: Don't set .props.:rum/state of the React component <our-src />. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props.
```

**Comment by currentoor** [comment]
Ok compiled and verified that the examples work.

**Comment by atroche** [comment]
good work! I ran into this same problem the other day and just decided to use reagent, because laziness.

**Comment by currentoor** [comment]
@atroche Thanks! I'll hopefully have a rum-material-ui wrapper on cljsjs before the end of the weekend. Don't join the dark side yet!

**Pull request merged**
