### PR TITLE
Define additional constructor that can setup React component props

### PR DESCRIPTION
**Pull request by ajchemist**
First of all, I conform `rum` state model, and constructing component in functional style. And It's good enough as much as I don't even have to know React.js to write sophisticated ui component.

By the way, yesterday I read https://facebook.github.io/react/docs/interactivity-and-dynamic-uis.html document for reference. then I realized `rum` doesn't have straightforward `props` interface.

As `rum` stands both low-level and high-level React.js api, so I think It's not a bad idea `rum` can setup React.js `props` when constructing element.

Originally, a component definition looks like 

``` clojure
(defc tree < rum/static
  ([form] (tree form 0)))
  ([form depth]
   (let [offset {:style {:margin-left (* 10 depth)}}]
     (if (sequential? form)
       [:.branch offset (map #(tree % (inc depth)) form)]
       [:.leaf   offset (str form)]))))
```

and It will **def** `tree` constructor that is writed in form of `(tree [:a [:b [:c :d [:e] :g]]])`

However, now we can also write a definition like this

``` clojure
(rum/defcc tree < rum/static > ;; highly inspired by the new rum front logo ;-)
  ([this form] (tree form (or (.. this -props -depth) 0)))
  ([this form depth]
   (let [offset {:style {:margin-left (* 10 depth)}}]
     (if (sequential? form)
       [:.branch offset (map #(tree % (inc depth)) form)]
       [:.leaf   offset (str form)]))))
```

and It will **def** both `tree` and `>tree` constructor. Specially `>tree` constructor can set component `props` data in form of `(>tree #js {:depth 2} [:a [:b [:c :d [:e] :g]]])`

I think the very `>constructor` can also be used in this way.

``` clojure
(defcc example > [this]
  [:div {:class (or (aget this "props" "class") "")}
   (aget this "props" "children")])

(>example #js {:class "xyz" :children (some-rum-element)})
```

This interface seems not ideal for cljs functional programming, but I think it's better than nothing ;-)

### CODE REVIEW

**Comment by tonsky** [comment]
Why would you need to setup props on Rum component? I’m looking for
rationale here

**Comment by ajchemist** [comment]
Hmm, sometimes I write a component like `example` above. It's not so much component as template.

until now, I wrote this way.

```
(defc example [props children] [:div (merge {:class "abc"} props) children])
```

This will store `props` and `children` arguments in state `:rum/args`, But `props` or `children` are just computed data.

I think arguments passed into rum component would be render-related data. and It seems that passing arbitrary children as argument is somewhat tricky.

Some real example below.

``` clojure
(defcs outblock-element
  < {:transfer-state
     (fn [old next]
       (-> next (assoc :rvpacket (:rvpacket old)) register-tr-subscription))
     :will-mount
     (fn [state] (-> state register-tr-subscription))}
  [{packet :rvpacket} {[_ & outblocks] :struct tr :tr real? :real? :as parsed} children]
  [:.sub-container
   (map (fn [[blkid & fields]]
          (let [blkname (name blkid)]
            [:.sub
             [:h6.blkname blkname]
             [:.table {:key blkname}]]))
        outblocks)
   [:.data
    (let [outblock-data (@(get packet tr) :data)]
      (pr-str outblock-data))]
   children])
```

``` clojure
(defcs outblock-element
  < {:transfer-state
     (fn [old next]
       (-> next (assoc :rvpacket (:rvpacket old)) register-tr-subscription))
     :will-mount
     (fn [state] (-> state register-tr-subscription))} >
  [{packet :rvpacket this :rum/react-component} {[_ & outblocks] :struct tr :tr real? :real? :as parsed}]
  [:.sub-container
   (map (fn [[blkid & fields]]
          (let [blkname (name blkid)]
            [:.sub
             [:h6.blkname blkname]
             [:.table {:key blkname}]]))
        outblocks)
   [:.data
    (let [outblock-data (@(get packet tr) :data)]
      (pr-str outblock-data))]
   (.. this -props -children)])
```

**Comment by ajchemist** [comment]
Hmm, hmmmm,,,
The more I'm keep seeking a critical example that explains rationale why props, the more I marvel at the power of rum abstraction :O

Let me think a little bit more.

**Comment by ajchemist** [comment]
@tonsky now I'm curious why we need `:class-properties`?

``` clojure
(let [msg-data   (volatile! "Components can store custom data on the underlying React component.")
      msg-method (fn [comp]
                   [:div {:style {:cursor "pointer"}
                          :on-mouse-move
                          (fn [_]
                            (vreset! msg-data (rand))
                            (rum/request-render comp))}
                    "Custom methods too. Hover me!"])]
  (rum/defcc custom [comp]
    [:div
     [:div @msg-data]
     [:div (msg-method comp)]]))
```

_clojure `atom` or `volatile!` mutation_ versus. _native js data mutation_ is the only difference I think.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Oh, `class-properties` have another use-case that deal with `childContextTypes`, ignore this.

**Comment by ajchemist** [comment]
``` clojure
;; some state processing fn
(defn register-tr-subscription
  [{args :rum/args component :rum/react-component :as state}]
  ...)

;; mixin
{:transfer-state
 (fn [old next]
   (-> next (assoc :rvpacket (:rvpacket old)) register-tr-subscription))
 :will-mount
 (fn [state] (-> state register-tr-subscription))}

;; some component
(defcs outblock-element < mixin [state arg1 arg2] ...)
```

If `arg1` should be processed via mixin in lifecycle, and `arg2` dont need to do so. then I feel `arg2` is right case for `props`.

So far I have to care `arg2`(mostly just position) in `register-tr-subscription`.

If `arg2` may be another rum component, is that ok storing a rum component in `outblock-element` state not just props?

**Comment by ajchemist** [comment]
@tonsky hmm you're right, `props` is useless in `defc`. After all, `props` will be used in interop case only which use other react lib's mixin that use `props`, then user can setup their component `props` directly through `rum/element`. 

I've ever not thought carefully about this `props` thing till now.

I will abort this PR if proper example would not been found.

**Comment by tonsky** [comment]
That’s my feeling too. If you need props and interop, go for raw React
components, not rum

**Comment by ajchemist** [comment]
Yep, thank you for advice.

**Pull request closed without merging**
