### PR TITLE
fix DCE of unused components

### LINKED ISSUE #128: How to optimize for Closure dead code removal?
My rum-using code is compiled into two different files, targeting different use cases via some compile-time constants.
Closure compiler is quite good at removing the dead (unused) code, so these two files contain only function they need.
However, that is not the case with rum components. Even when they are not used, they don't get trimmed away because of the way they are declared.
Let's see. These are two components that are not used anywhere (except `test-component2` in `test-component`):

```clojure
(rum/defc test-component2 []
  [:div.test-component2 "TEST COMP2"])

(rum/defc test-component []
  [:div.test-component "TEST COMP" (test-component2)])
```

This gets compiled into:
```javascript
l$=function(){var a=rU(function(){return React.createElement("div",{className:"test-component2"},"TEST COMP2")}),b=mU(O.j(new J(null,1,5,K,[a],null),null),"test-component2");return Wd(function(a,b){return function(){function a(b){var d=null;if(0<arguments.length){for(var d=0,e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new z(e,0)}return c.call(this,d)}function c(a){return uU(b,
tU(a))}a.A=0;a.B=function(a){a=w(a);return c(a)};a.o=c;return a}()}(a,b),new g(null,1,[br,b],null))}();

(function(){var a=rU(function(){var a=Z(l$.v?l$.v():l$.call(null));return React.createElement("div",{className:"test-component"},"TEST COMP",a)}),b=mU(O.j(new J(null,1,5,K,[a],null),null),"test-component");return Wd(function(a,b){return function(){function a(b){var d=null;if(0<arguments.length){for(var d=0,e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new z(e,0)}return c.call(this,d)}function c(a){return uU(b,tU(a))}a.A=0;a.B=function(a){a=w(a);return c(a)};a.o=c;return a}()}(a,
b),new g(null,1,[br,b],null))})();
```

As you can see, the Closure compiler has detected that the `test-component` is not used anywhere, so it didn't assign a return value to a var (like it did with `$l=` for the first component).
But the whole function call with component creation is left intact, yet unneeded.

Does anybody have an idea how to make Closure compiler remove those?
I've tried adding some hints to the extern file, yet they don't change anything:
```javascript
var rum;
/** @nosideeffects */
rum.core.element = function() {};
/** @nosideeffects */
rum.core.build_class = function() {};
/** @nosideeffects */
rum.core.render_state__GT_mixin = function() {};
/** @nosideeffects */
rum.core.args__GT_state = function() {};
```

I know I can wrap component declarations in `(when CONSTANT (rum/defc ...))`, but that require tracking down whole components call stack.

### PR DESCRIPTION
**Pull request by roman01la**
Reviving #145

@martinklepsch @piranha Do you remember if there were any issues with delayed components approach? What about metadata?

### CODE REVIEW

**Comment by martinklepsch** [comment]
I don't remember any issues but I also don't remember testing this extensively. If this repo had a deps.edn I'd be happy to give this a try in our production app.

**Comment by sansolovyov** [comment]
We're using them since ages, but I don't think we ever touched metadata there. What kind of metadata though? If you're thinking about React's names etc, then it works. If about `with-meta` stuff, then no idea. :) But I can check if you have an idea of what to check. :)

**Comment by roman01la** [comment]
> We're using them since ages, but I don't think we ever touched metadata there. What kind of metadata though? If you're thinking about React's names etc, then it works. If about `with-meta` stuff, then no idea. :) But I can check if you have an idea of what to check. :)

Hmm, alright. So you are saying you are already using exactly same implementation, right?

**Comment by sansolovyov** [comment]
What we use, clj side:

```
(ns mk.common.rum-patch)

(in-ns 'rum.core)

(defn- -defc [builder cljs? body]
  (let [{:keys [name doc mixins bodies]} (parse-defc body)
        render-body (if cljs?
                      (map compile-body bodies)
                      bodies)
        arglists  (if (= builder 'rum.core/build-defc)
                    (map (fn [[arglist & _body]] arglist) bodies)
                    (map (fn [[[_ & arglist] & _body]] (vec arglist)) bodies))]
    (if cljs?

      `(def ~(vary-meta name update :arglists #(or % `(quote ~arglists)))
         ~@(if doc [doc] [])
         (mk.common.rum-patch/lazy-component ~builder (fn ~@render-body) ~mixins ~(str name)))

      `(def ~(vary-meta name update :arglists #(or % `(quote ~arglists)))
         ~@(if doc [doc] [])
         (~builder (fn ~@render-body) ~mixins ~(str name))))))
```

CLJS side:

```
(ns mk.common.rum-patch)

(defn lazy-component
  "Support for mk.render.rum-patch, which makes all components lazy-initialized"
  [ctor a b c]
  (let [c (delay (ctor a b c))]
    (fn []
      (.apply @c @c (js-arguments)))))
```

**Comment by roman01la** [comment]
added tests to make sure that meta is added to components

**Pull request merged**
