### PR TITLE
Sablono update to 0.6.0

### PR DESCRIPTION
**Pull request by niwinz**
I have recompied the example code for check if everything working as expected.

### CODE REVIEW

**Comment by tonsky** [comment]
is react-dom-server required here? why?

**Comment by niwinz** [comment]
I don't know but sablono requires it.

**Comment by tonsky** [comment]
@r0man says it’s not required https://github.com/r0man/sablono/issues/93

**Comment by niwinz** [comment]
Updated pr with sablono 0.6.0 and now without react-dom-server dependency.

**Comment by tonsky** [comment]
Great to see it has been resolved. I bumped version [here](https://github.com/tonsky/rum/commit/a6fb0efe28b4691e3ac8e318d03e1f2dc0849a23), I’ll merge it when that branch gets merged. Thanks!

**Comment by niwinz** [comment]
:+1:

**Pull request closed without merging**
