### PR TITLE
Fragments support

### PR DESCRIPTION
**Pull request by DjebbZ**
This time for real. My simple implementation seems to work well (at least it passes the test).

This needs more tests maybe, examples and Readme update at least.

### CODE REVIEW

**Comment by solidfox** [comment]
Really looking forward to this. Wish I had the time to help you out with more tests. Maybe this weekend.

**Comment by DjebbZ** [comment]
I think we're close to fully support them. Need more manual/automated testing I think. Especially the case with several  top fragments level. Maybe others.

**Comment by PEZ** [comment]
What's the status for this?

**Comment by DjebbZ** [comment]
I personally haven't had time to finish the PR. I'm sure it's close though,
if you want to take a look.

**Comment by roman01la** [comment]
Hello 👋 New maintainer here.

We'll most likely pull in Sablono into the repo some time in the future (see https://github.com/tonsky/rum/issues/198), so this will be addressed later for both JS and JVM targets. The plan is to have `:<>` Hiccup tag instead.

**Comment by roman01la** [comment]
`fragment` component has landed on master, we'll stick with a macro for now

**Pull request closed without merging**
