### PR TITLE
Content: Add simply to Who's using Rum list

### PR DESCRIPTION
**Pull request by domparry**
Simply is using Rum too, and would like to give credit.

### CODE REVIEW

**Comment by tonsky** [comment]
Where is it used? Can’t find it in any of the app sources

**Comment by domparry** [comment]
Hey,

Sorry, I didn’t specify the apps. We link to both from our home page:

https://obelix.simply.co.za/ <https://obelix.simply.co.za/login>
https://www.group.simply.co.za/


Kind Regards,
Dom Parry
0828236887

Sent from  Astro <https://www.helloastro.com/>  for Mac

On 06 Nov 2017 at 14:43, Nikita Prokopov <notifications@github.com> wrote:


Where is it used? Can’t find it in any of the app sources

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tonsky/rum/pull/153#issuecomment-342137658>, or mute
the thread

**Comment by tonsky** [comment]
Thanks!

**Comment by domparry** [comment]
Apologies, Obelix isn’t linked from the website. That’s our call centre
front end...


Kind Regards,
Dom Parry
0828236887

Sent from  Astro <https://www.helloastro.com/>  for Mac

On 06 Nov 2017 at 14:50, Dominic Parry <dom.parry@gmail.com> wrote:


Hey,

Sorry, I didn’t specify the apps. We link to both from our home page:

https://obelix.simply.co.za/ <https://obelix.simply.co.za/login>
https://www.group.simply.co.za/


Kind Regards,
Dom Parry
0828236887

Sent from  Astro <https://www.helloastro.com/>  for Mac

On 06 Nov 2017 at 14:43, Nikita Prokopov <notifications@github.com> wrote:


Where is it used? Can’t find it in any of the app sources

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tonsky/rum/pull/153#issuecomment-342137658>, or mute
the thread

**Pull request merged**
