### PR TITLE
Sablono fork & Remove render queue

### LINKED ISSUE #198: Remove Sablono dependency, do templating internally
Rum batches all updates and applies them all at once on requestAnimationFrame.

This doesn’t work well with DOM/React input fields and controlled values: they need re-render synchronously, otherwise you’ll see junk while typing in input field, selection will be broken, etc.

Sablono has special code that wraps every input in a wrapper that does that synchronous update directly in place, without waiting for next frame or anything. Problem is, this code adds complexity, is not entirely transparent, and doesn’t work very well. We’ve worked with r0man tried to fix it a few times (https://github.com/r0man/sablono/pull/129, https://github.com/r0man/sablono/pull/127, https://github.com/r0man/sablono/pull/123) but ultimately we didn’t succeeded. In fact, I believe it is still broken somehow in 0.8.6, and that’s the reason why Rum stays on Sablono 0.8.1 instead.

Now, it all can be solved much easier if Sablono could call Rum re-render from input handlers. You wouldn’t need wrappers, I believe. Problem is, Sablono doesn’t know anything about Rum.

Solution I propose: remove Sablono dependency and implement templating entirely inside Rum. That would allow for much simpler and (hopefully) finally working inputs code.

Another benefit would be that server-rendering code would more closely match client-rendering code with regards to e.g. nil handling etc (https://github.com/r0man/sablono/pull/132).

It will also allow us to fix some issues that are pending in Sablono as it seems not to be actively maintained, e.g. https://github.com/r0man/sablono/issues/201

### PR DESCRIPTION
**Pull request by roman01la**
Resolves #198

- Fork Sablono
  - Remove unnecessary code
  - Simplify and improve interpreter perf
- Go away from Rum's render queue and `.forceUpdate` re-rendering model

`[rum "0.12.0-SNAPSHOT"]`
`rum {:mvn/version "0.12.0-SNAPSHOT"}`

## TESTING
- JVM SSR should work
- Typing into input fields should work w/o glitches
- Anything related to local and reactive state updates should work as expected

### CODE REVIEW

**Comment by roman01la** [comment]
If you already tested `0.11.5-SNAPSHOT` and it works fine for you, give a try to `0.12.0-SNAPSHOT` which includes a major update described above.

cc @piranha @martinklepsch @DjebbZ @sergmarch

**Comment by zelark** [comment]
@roman01la, checked #181, it's gone now.

**Comment by roman01la** [comment]
> @roman01la, checked #181, it's gone now.

Nice! Hopefully relying on React's scheduling mechanism we can finally solve issues related to inputs.

**Comment by roman01la** [comment]
Btw, for this and future testing it would be great to compile a list of open source projects that depend on Rum, so we could rum their test suits against Rum (if they have tests of course). Any pointers to such projects?

#208

**Comment by ikitommi** [comment]
What happens if user has dependency also to sablono - which code is used? Should the forked version be in a separate ns like `rum.sablono.*`?

**Comment by roman01la** [comment]
> What happens if user has dependency also to sablono - which code is used? Should the forked version be in a separate ns like `rum.sablono.*`?

Yes, I'll rename those namespaces later.

**Comment by roman01la** [comment]
👋 @drikerf Mentioning you since you are the most recent user of Rum according to our readme.

**Comment by drikerf** [comment]
>  @drikerf Mentioning you since you are the most recent user of Rum according to our readme.

Hey! I just tested `0.12.0` in staging and everything seems to work great. I have a marketing page which is rendered on the server and then hydrated and the app which is just client rendered.

Thanks for doing this! And let me know if there's anything specific you want me to test, or other ways I could help out :).

**Comment by roman01la** [comment]
@drikerf Thanks! Glad to hear that it works for you. There's 3 things I'd like to test, they are listed in the PR's description above.

**Comment by drikerf** [comment]
> @drikerf Thanks! Glad to hear that it works for you. There's 3 things I'd like to test, they are listed in the PR's description above.

- [x] JVM SSR
- [x] Inputs
- [x] State works as expected. Though I pass one state atom from the root down as a prop and use no local/reactive states.

**Comment by roman01la** [comment]
@drikerf Thanks a lot!

**Comment by sergmarch** [comment]
@roman01la I've checked `"0.12.0-SNAPSHOT"` and everything works as expected. 
Checked:
- SSR
- Text input fields
- Local & reactive states

**Comment by DjebbZ** [comment]
With all the pandemic/quarantine stuff and its impact on work, I'm a bit late to the party but still pleased to announce that we migrated from `0.11.3` to `0.11.5` successfully, `0.11.5` is now in production, no bug found during our testing and no code needed to be changed !

Next-up hopefully this week I'll play with `0.12.0-SNAPSHOT` locally and see how it goes. I'll report here.

**Comment by DjebbZ** [comment]
By the way, we're using rum with citrus, and excluded rum from citrus (since citrus by default brings its own version of rum). citrus 3.2.3 (latest) works fine with rum 0.11.5. We'll see with rum 0.12.0-SNAPSHOT.

**Comment by DjebbZ** [comment]
Looks KO at first sight, I have an error, I haven't had the time to deep-dive on it but I had a subscription with a derived-atom that simply crashed client-side (server-side the page worked OK it seems). I will do further investigation, hopefully this week. I don't even know if it's rum alone or the combo rum+citrus.

**Comment by roman01la** [comment]
Merging this into master and cutting a release
@DjebbZ Please report bugs in a separate issue

**Comment by DjebbZ** [comment]
Just wanted to mention that I'm not working at the same place anymore and I don't think I'll be using rum. So let me ping @bfontaine member of the team, he'll take care of the rest. Keep up the good work!

**Pull request merged**
