### PR TITLE
Allow mixins to be a vector maps, or one flat map.

### PR DESCRIPTION
**Pull request by chrisetheridge**

### CODE REVIEW

**Comment by chrisetheridge** [comment]
Input data:

```clj
(let [mixins-vector [{:before-render (fn [state] (assoc state ::cat "dog"))}
                     {:will-mount    (fn [state] (assoc state ::pig "moo"))}]
      mixins-map    {:before-render (fn [state] (assoc state ::cat "dog"))
                     :will-mount    (fn [state] (assoc state ::pig "moo"))}
      keys          [:before-render :will-mount]
      collect-patch (fn [keys mixins]
                      (->> (mapcat (fn [m]
                                     (if-not (map? m)
                                       (let [m (assoc {} (first m) (second m))]
                                         (map (fn [k] (get m k)) keys))
                                       (map (fn [k] (get m k)) keys))) mixins)
                           (remove nil?)))]
  (clojure.pprint/pprint
   {:vector (collect* keys mixins-vector)
    :map    (collect* keys mixins-map)
    :custom-vector (collect-patch keys mixins-vector)
    :custom-map (collect-patch keys mixins-map)}))
```

Output:

```clj
{:vector
 (#function[rum.util/eval25498/fn--25499]
  #function[rum.util/eval25498/fn--25501]),
 :map (),
 :custom-vector
 (#function[rum.util/eval25498/fn--25499]
  #function[rum.util/eval25498/fn--25501]),
 :custom-map
 (#function[rum.util/eval25498/fn--25503]
  #function[rum.util/eval25498/fn--25505])}
nil

```

Using current `collect*` and my patched `collect*`.

**Comment by chrisetheridge** [comment]
`collect*` seems break when doing the following:

```clj
(rum/defcs counter < {:before-render
                      (fn [state]
                        (assoc state ::foo "bar"))
                      :will-mount
                      (fn [state]
                        (assoc state ::bar "baz"))}
  [state]
  (prn (::bar state) (::foo state)))
```

But, this works (note, using 2 maps instead of one):

```clj
(rum/defcs counter < {:before-render
                      (fn [state]
                        (assoc state ::foo "bar"))}
                     {:will-mount
                      (fn [state]
                        (assoc state ::bar "baz"))}
  [state]
  (prn (::bar state) (::foo state)))
```

**Comment by chris-etheridge** [comment]
Temporarily closing this.

**Comment by tonsky** [comment]
No, `collect*` as it is seems to be fine:

```
(collect* [:a :b] [{ :a 1 :b 2 }]) => (1 2)
```

Note that mixins is _always_ a vector of maps

**Comment by chris-etheridge** [comment]
Ah, so

**Pull request closed without merging**
