### PR TITLE
Add React 16.3-4 APIs

### PR DESCRIPTION
**Pull request by roman01la**
This PR is a WIP on adding wrappers for new APIs introduced in React v16.3-4 (see tracking issue #165 and [changelog](https://github.com/facebook/react/blob/master/CHANGELOG.md#1632-april-16-2018) for a full list of changes in React).

Below is a list of implemented features so far. Feel free to comment and start discussion.

## Context API
On ClojureScript side this is a simple wrapper on top of existing JS API in React.

For server-side rendering in Clojure JVM I've implemented Context API via `clojure.core/binding`, since essentially an instance of React's Context is a shared global variable that is bound to provided value for current execution scope via React's adhoc API.

```clojure
(def ^:dynamic *color-theme*
  (rum/create-context "#000"))

(rum/defc rum-comp [color]
  [:span
    { :style { :color color }}
    "Child component uses context to set font color."])

(rum/defc rum-context-comp []
  (rum/with-context *color-theme* rum-comp))

(rum/defc context []
  [:div
    [:div "Root component implicitly passes data to descendants."]
    (rum/provide-context *color-theme* "#ff0000" (rum-context-comp))])
```

#### `^:dynamic` context var
Because context bound var should be dynamic for SSR I decided to be consistent and make it so for ClojureScript as well. While it might be an additional overhead and source of questions I think it is idiomatic for Clojure since React's Context is essentially a dynamic global var.

#### `rum.core/provide-context` and `rum.core/provide-context-clj`
`clj` version of `rum.core/provide-context` is implemented as a macro because we need to know that dynamic var at compile time to produce proper `binding` form and also the next value in Context should be set before child component is instantiated. This works fine in JS React because actual rendering happens there after all components have been instantiated, but in Clojure JVM Rum first builds entire UI tree as Hiccup and during this process everything gets evaluated.

Now, because of how ClojureScript's compiler works it's impossible to require a function into `cljs` ns from a namespace that has a macro in `clj` version and a function in `cljs` version both with the same name, macro always gets required. A workaround is to distinct that macro and function with different names.

I've decided to name the macro with `clj` suffix `rum.core/provide-context-clj` and keep ClojureScript function with normal name because I assumed that Context API is probably more often used on the client/cljs than with SSR, given that SSR is done less often than client-only apps.

#### Differences from React API
Unlike `Context.Provider` in React.js, `rum.core/provide-context` in Rum takes only a single child, because Rum doesn't support fragments yet (blame Sablono).

## Lifecycles
Two new lifecycles were added, non of existing were removed. These are "safe" lifecycles for upcoming async rendering mode in React. They meant to be a replacement for `componentWillMount` (`:will-mount`, `:before-render`), `componentWillReceiveProps` (`:did-remount`) and `componentWillUpdate` (`:will-update`, `:before-render`).

### `:derive-state` -> `static getDerivedStateFromProps`
Allows modifying component's state before both initial and subsequent calls to render fn. Get's called when rendering on server as a part of initialization phase (same as `:will-mount` does).

### `:make-snapshot` -> `getSnapshotBeforeUpdate`
Mainly for side-effects to be performed right before DOM is updated. Anything added to `:rum/snapshot` in component's state will be passed into `:did-update` as the second argument.

```clojure
(rum/defc snapshot <
  {:make-snapshot
   (fn [st]
     (assoc st :rum/snapshot (.-innerWidth js/window)))
   :did-update
   (fn [st snapshot]
     (let [node (rum/ref-node st :snapshot)]
       (set! (.. node -textContent) (str "snapshot: " snapshot)))
     st)}
  []
  [:div {:ref :snapshot} "snapshot: "])
```

Because React disallows usage of both "legacy" and new lifecycles the following changes were made:

- `rum.core/local` now uses `:init` lifecycle to initialize state instead of `:will-mount`
- `:did-update` and `:after-render` lifecycles became two arity functions, bc `:did-update` now receives optional second argument which is `snapshot` value computed in `:make-snapshot` lifecycle. `snapshot` argument is `nil` in `:after-render` when called on `:did-mount`.

## Ref API
Provided wrapper for `React.createRef` API and helpers similar to existing ones in Rum. API wrapper is needed only for convenience in server-side rendering to avoid conditional directives.

```clojure
(def input (rum/create-ref))

;; ...
[:input {:ref input}]

;; ...
{:did-mount
  (fn [s]
    (.focus (rum/current-ref-node input))
    s)}
```

### CODE REVIEW

**Comment by roman01la** [comment]
Adding migration notes while testing

- `:will-mount` -> `:did-mount`
- `:will-mount` + `:will-update` -> `:derive-state`

**Comment by tonsky** [comment]
Why do we need make-snapshot and snapshot in did-update at all? Can be solved by a combination of before-update + after-update, no?

**Comment by roman01la** [comment]
@tonsky

In short: the new API works towards async rendering in React v17, which is not compatible with some of currently used lifecycles because of how reconciliation algorithm works in React when in async mode.

> Why do we need make-snapshot

`:make-snapshot` is using a new React's lifecycle `getSnapshotBeforeUpdate` which is completely different from `:before-render` and `:after-render` which corresponds to `componentWillMount`, `componentWillUpdate`, `componentDidMount` and `componentDidUpdate`. Both `componentWillMount` and `componentWillUpdate` are considered deprecated lifecycles since v16.4.

So basically simulating new async-aware lifecycles won't do the job.

`:make-snapshot` could be done via `:before-render` and `:after-render`, but it couldn't because `:before-render` is using deprecated `componentWillMount` and `:after-render` is using `componentDidMount` which is not when `getSnapshotBeforeUpdate` executes (it executes inly on subsequent updates)

> ...and snapshot in did-update at all?

> getSnapshotBeforeUpdate() is invoked right before the most recently rendered output is committed to e.g. the DOM. It enables your component to capture some information from the DOM (e.g. scroll position) before it is potentially changed. Any value returned by this lifecycle will be passed as a parameter to componentDidUpdate().

see [React docs](https://reactjs.org/docs/react-component.html#getsnapshotbeforeupdate)

**Comment by DjebbZ** [comment]
At first glance, it looks good. Don't have time to try it in my current project, but maybe in a few weeks.

**Pull request closed without merging**
