### PR TITLE
Arglists metadata for ctor defined by defc* macros

### PR DESCRIPTION
**Pull request by ajchemist**
for repl dev experience.

### CODE REVIEW

**Comment by tonsky** [comment]
Not sure how it works, but I emit `def` from `defc`, shouldn’t `def` take care of generating proper :arglists meta?

**Comment by ajchemist** [comment]
``` clojure
(set! *print-meta* true)

;; It seems followings are equivalent

(def ^{:arglists '([x] [x y])} a (fn ([x] :x) ([x y] :y)))
(:arglists (meta #'a))

(doto (def b (fn ([x] :x) ([x y] :y)))
  (alter-meta! assoc :arglists '([x] [x y])))
(:arglists (meta #'b))

(eval (list 'def (with-meta 'c {:arglists ''([x] [x y])}) '(fn ([x] :x) ([x y] :y))))
(:arglists (meta #'c))

;; and this is not

(def d (fn ([x] :x) ([x y] :y)))
(:arglists (meta #'d)) 
```

**Comment by ajchemist** [comment]
@tonsky ping (force revision)

**Comment by ajchemist** [comment]
screen shot 2016-04-20 at 6 12 27 pm

**Comment by tonsky** [comment]
Yeah, that’s my bad — arglists is populated by defn, and I’m emiting def

**Comment by tonsky** [comment]
Released as 0.8.1

**Pull request merged**
